src/WebApp/Viewer/urls.py
from django.conf.urls import patterns, url

from Viewer import views


urlpatterns = patterns('',
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    url(r'^loader/$', views.loader, name='loader'),
)

src/WebApp/WONKA/urls.py
from django.conf.urls import patterns, url
from WONKA import views

urlpatterns = patterns('',
    url(r'^(?P<target_id>\d+)/NewComplex/$', views.NewComplex, name='NewComplex'),
    url(r'^(?P<target_id>\d+)/Summarise/$', views.Summarise, name='Summarise'),
        url(r'^(?P<target_id>\d+)/SummariseORIG/$', views.SummariseORIG, name='SummariseORIG'),

    url(r'^(?P<target_name>\w+)/SummariseCheck/$', views.SummariseCheck, name='SummariseCheck'),
    url(r'^(?P<obs_id>\d+)/SummariseBack/$', views.SummariseBack, name='SummariseBack'),
    url(r'^ScoreMol/$', views.ScoreMol, name='ScoreMol'),
    url(r'^show_point/$', views.show_point, name='show_point'),
    url(r'^register_observation/$', views.register_observation, name='register_observation'),
    url(r'^register_user/$', views.register_user, name='register_user'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^add_comment/$', views.add_comment, name='add_comment'),
    url(r'^(?P<prot_id>\d+)/get_grob/$', views.get_grob, name='get_grob'),
    url(r'^get_interactions/$', views.get_interactions, name='get_interactions'),
    url(r'^request_observation/$', views.request_observation, name='request_observation'),
    url(r'^(?P<target_id>\d+)/ShowObservations/$', views.ShowObservations, name='ShowObservations'),
    url(r'^(?P<target_id>\d+)/fp_view/$', views.fp_view, name='fp_view'),
    url(r'^get_targ_fps/$', views.get_targ_fps, name='get_targ_fps'),
    url(r'^mol_view/$', views.mol_view, name='mol_view'),
    url(r'^(?P<target_id>\d+)/SplitSet/$', views.SplitSet, name='SplitSet'),
    url(r'^(?P<target_id>\d+)/view_clusts/$', views.view_clusts, name='view_clusts'),
    url(r'^(?P<target_id>\d+)/get_cluster/$', views.get_cluster, name='get_cluster'),
    url(r'^get_pot_ph4s/$', views.get_pot_ph4s, name='get_pot_ph4s'),
    url(r'^seen_mol/$', views.seen_mol, name='seen_mol'),
    url(r'^(?P<target_id>\d+)/get_frags/$', views.get_frags, name='get_frags'),
    url(r'^(?P<uuid>[^/]+)/ShowObs/$', views.ShowObs, name='ShowObs'),
    url(r'^(?P<user_pk>\d+)/get_user_info/$', views.get_user_info, name='get_user_info'),
    
    url(r'^(?P<cluster_pk>\d+)/get_oommppaa_infos/$', views.get_oommppaa_infos, name='get_oommppaa_infos'),
    url(r'^(?P<target_id>\d+)/(?P<user_id>\d+)/unsubscribe_targ/$', views.unsubscribe_targ, name='unsubscribe_targ'),
    url(r'^(?P<target_id>\d+)/(?P<user_id>\d+)/subscribe_targ/$', views.subscribe_targ, name='subscribe_targ'),
    url(r'^subscribe_to_disqus/$', views.subscribe_to_disqus, name='subscribe_to_disqus'),
    url(r'^FindObservations/$', views.FindObservations, name='FindObservations'),
    url(r'^(?P<mol_id>\d+)/get_map/$', views.get_map, name='get_map'),
    url(r'^$', views.index, name='index'),
)

src/WebApp/WebApp/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
# Uncomment the next two lines to enable the admin:
#from django.contrib import admin
#admin.autodiscover()
import views
urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^Viewer/', include('Viewer.urls',namespace="Viewer")),
#    url(r'^SUPERSTAR/', include('SUPERSTAR.urls',namespace="SUPERSTAR")),
    #url(r'^GLOOP/', include('GLOOP.urls',namespace="GLOOP")),
    url(r'^OOMMPPAA/', include('OOMMPPAA.urls',namespace="OOMMPPAA")),
    #url(r'^LLOOMMPPAA/', include('LLOOMMPPAA.urls',namespace="LLOOMMPPAA")),
    url(r'^WONKA/', include('WONKA.urls',namespace="WONKA")),
#    url(r'^admin/', include(admin.site.urls)),
    url( r'^upload/', views.upload, name = 'jfu_upload' ),
    url(r'^run/$', views.run, name='run'),
)+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/WebApp/WONKA/views.py
from django.shortcuts import render, get_object_or_404
# Import the models
from IOhandle.models import Protein,Target,Project,Molecule,ActivityPoint,Compound
from MMPMaker.models import MMPDiffMap
from WebApp.settings import DATABASES
import json
from rdkit import Chem
from rdkit.Chem import AllChem
from WONKA.models import Residue, PharmaScore, FragScore, KeyCluster, ResShift,InternalIDLink
from OBSERVATIONS.models import Observation, Comment, UserData, ObservationChoices
from WONKA.functions import render_pharma_pdb
import bisect, urllib
from django.http import HttpResponse, HttpResponseRedirect
from Pharmacophore.models import PharmaPoint
from rdkit.ML.Cluster import Butina
from rdkit import SimDivFilters,DataStructs
from rdkit.Chem import rdMolDescriptors
import numpy
from rdkit.DataManip.Metric import rdMetricMatrixCalc
from django.core import serializers
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.contrib.auth import authenticate, login, logout
from rdkit.Chem import Draw
import StringIO
# Import smtplib for the actual sending function
import smtplib, hashlib
import struct, uuid
# Import the email modules we'll need
from email.mime.text import MIMEText
import random
from WONKA.functions import find_res_rmsd
from MMPMaker.models import Act3DFrag, ActPharmaPoint
from Viewer.models import eucl_dist
import math, ast
from django.db.models import Q
from rdkit.Chem import MCS
from djutils.decorators import async


def FindObservations(request):
    """Function to find observations given a given series of mol ids, compound ids etc"""
    # Get the host
    host = request.get_host()
    # Get the targets
    targets = Target.objects.exclude(title="DUMMY")
    # First get all the relevant IDs
    mol_ids = [int(x) for x in request.GET["mol_id"].split(",") if x]
    cmpd_ids = [Molecule.objects.get(pk=int(x)).cmpd_id.pk for x in request.GET["mol_id"].split(",") if x]
    target_id = int(request.GET["target_id"])
    water_ids = [int(x) for x in request.GET["water_id"].split(",") if x]
    ph4_ids = [int(x) for x in request.GET["ph4_id"].split(",") if x]
    prot_ids = [int(x) for x in request.GET["prot_id"].split(",") if x]
    # Now get the things that match all
    obs_c = ObservationChoices.objects.filter()
    for my_id in mol_ids:
        # Now filter this
        obs_c = obs_c.filter(mol_id=my_id)
    # Get all the observations info
    match_all_obs = Observation.objects.filter(pk__in=obs_c.values_list("obs_id", flat=True))
    mol_obs = Observation.objects.exclude(pk__in=match_all_obs).filter(pk__in=ObservationChoices.objects.filter(mol_id__in=mol_ids).values_list("obs_id", flat=True))
    cmpd_obs = Observation.objects.exclude(pk__in=mol_obs).exclude(pk__in=match_all_obs).filter(pk__in=ObservationChoices.objects.filter(cmpd_id__in=cmpd_ids).values_list("obs_id", flat=True))
    # Get the ones to show
    for ob in mol_obs:
        ob.my_src = "http://" + host + '/WONKA/request_observation/?my_pk=' + str(ob.pk) + '&me=dl.icb'
    for ob in cmpd_obs:
        ob.my_src = "http://" + host + '/WONKA/request_observation/?my_pk=' + str(ob.pk) + '&me=dl.icb'
    for ob in match_all_obs:
        ob.my_src = "http://" + host + '/WONKA/request_observation/?my_pk=' + str(ob.pk) + '&me=dl.icb'
    # Get the ones to show info for
    # Now loop through and
    context = {"mol_obs": mol_obs,
               "targets": targets,
               "match_all_obs": match_all_obs,
               "cmpd_obs": cmpd_obs}
    return render(request, 'WONKA/FindObservations.html', context)


def seen_mol(request):
    """View to like a molecule for a person"""
    # Get the 
    mol_pk = int(request.GET["mol_pk"])
    # Get the user pk
    user_pk = int(request.GET["user_pk"])
    # Now get the user 
    user = User.objects.get(pk=user_pk)
    # Now get the data
    user_d = UserData.objects.get(user_id=user)
    # Get the molecule
    mol = Molecule.objects.get(pk=mol_pk)
    # Remove it from the list
    user_d.new_mols.remove(mol)
    # Now return this
    return HttpResponse(json.dumps({"mol_pk": mol_pk}))


def get_user_info(request, user_pk):
    """Get the target information for the user"""
    # Get the user from this
    user = User.objects.get(pk=user_pk)
    # Now get the user data for this one
    user_d = UserData.objects.get(user_id=user)
    targets = Target.objects.exclude(title="DUMMY")
    out_d = {}
    out_d["targs"] = []
    out_d["mols"] = []
    for targ in targets:
        new_d = {"name": targ.title}
        new_mols = user_d.new_mols.filter(prot_id__target_id=targ.pk)
        new_d["tot_new"] = len(new_mols)
        new_d["pk"] = targ.pk
        new_d["new"] = bool(len(user_d.new_targs.filter(pk=targ.pk)))
        new_d["cool"] = bool(len(user_d.cool_targs.filter(pk=targ.pk)))
        mols = Molecule.objects.filter(prot_id__target_id=targ).exclude(prot_id__code__contains=targ.title)
        new_d["mols"] = len(mols)
        # Get the activity points
        acts = ActivityPoint.objects.filter(target_id=targ)
        new_d["acts"] = len(acts)
        out_d["targs"].append(new_d)
        for mol in mols:
            out_d["mols"].append({"smiles": mol.smiles,
                                  "target": mol.prot_id.target_id.title,
                                  "pk": mol.pk,
                                  "cmpd_pk": mol.cmpd_id.pk,
                                  "new": bool(len(user_d.new_mols.filter(pk=mol.pk)))
                                  })
    return HttpResponse(json.dumps(out_d))


@async
def send_email(message, subject):
    """Function to send an e-mail - when users register or whartevs """
    # Create a text/plain message
    try:
        from WebApp import personalsettings as es
    except:
        print "YOU MUST SUPPLY E-MAIL AND PASSWORD"
        return
    # me == the sender's email address
    # you == the recipient's email address
    # Send the message via our own SMTP server.
    if es.email is None or es.password is None:
        print "YOU MUST SUPPLY E-MAIL AND PASSWORD"
        return
    e_mail = es.email
    msg = "\r\n".join([
  "From: " + e_mail,
  "To: " + e_mail,
  "Subject: " + subject,
  "",
  message
    ])
    username = e_mail
    password = es.email_password
    try:
        server = smtplib.SMTP('smtp.gmail.com:587', timeout=3)
    except:
        return
    server.starttls()
    server.login(username, password)
    server.sendmail(e_mail, e_mail, msg)
    server.quit()


def index(request):
    targets = Target.objects.exclude(title="DUMMY")#.filter(title="CDK2")
    projects = Project.objects.all()
    # No projects at the moment as this hasn't been set up yet
    context = {"targets": targets, "projects": None}
    return render(request, 'WONKA/index.html', context)


def cov_col(my_col, max_num=2.0):
    """Function to take a float and convert it to a HEX color on a heat map"""
    # First cutoff at -2 and +2
    my_col = min(my_col, max_num)
    my_col = max(my_col, -max_num)
    my_col += max_num
    max_num += max_num
    out_t = ((max_num - my_col) * 255 / max_num, my_col * 255 / max_num, 0)
    out_h = '#%02x%02x%02x' % out_t
    return out_h


def get_oommppaa_infos(request, cluster_pk):
    """View to take a cluster PK and return OOMMPPAA data for that target from like points nearby"""
    # Get the cluster
    dist = 1.5#float(request.GET["dist"])
    kc = KeyCluster.objects.get(pk=cluster_pk)
    # Get all like points from OOMMPPAA
    if kc.type == "MMPFrag object":
        # Filter down to just this type
        dist = 2.5
        act3dfrags = Act3DFrag.objects.filter(act_id__target_id=kc.target_id, mmp_frag_id__smistore=kc.function)#mmp_dict[kc.function]) LEAVE FOR NOW
        print len(act3dfrags)
        # Now filter these down to within 1A of the cluster centre
        out_vals = [x.actpharmapoint_set.all()[0].act_change for x in act3dfrags if eucl_dist(x.mmp_frag_id, kc) < dist]
    elif kc.type == "PharmaPoint object":
        # Filter  down to just this type
        actpps = ActPharmaPoint.objects.filter(in_diff_15=True, num_diff_15__lte=6, target_id=kc.target_id, pharma_id__smiles=kc.function)#pp_dict[kc.function]) LEAVE FOR NOW
        print len(actpps)
        # Now filter these down to distance
        out_vals = [x.act_change for x in actpps if eucl_dist(x.pharma_id, kc) < dist]
        print [eucl_dist(x.pharma_id, kc) for x in actpps]
    if len(out_vals) == 0:
        # If it's an empty list
        return HttpResponse(json.dumps({"outcome": "error", "pk": cluster_pk}))
    # Return summary information about this group
    out_vals = sorted(out_vals, reverse=True)
    out_d = {"mean": sum(out_vals) / len(out_vals),
             "min": min(out_vals),
             "max": max(out_vals),
             "stdev": numpy.std(out_vals),
             "num": len(out_vals),
             "vals": out_vals,
             # Get the colors for these buttons
             "colors": [cov_col(x) for x in out_vals],
             "pk": cluster_pk
             }
    return HttpResponse(json.dumps(out_d))


def get_cluster(request, target_id):
    """Function to get all the clusters given a lam and a type"""
    # Get the lam
    lam = float(request.GET["lam"])
    # Get the method
    method = str(request.GET["method"]) + " object"
    kcs = KeyCluster.objects.filter(type=method)
    kcs = kcs.filter(lam=lam)
    kcs = kcs.filter(target_id=target_id)
    if "smiles" in request.GET:
        my_mol = Chem.MolFromSmiles(str(request.GET["smiles"]))
        kcs = kcs.filter(function=Chem.MolToSmiles(my_mol, isomericSmiles=True))
    # Get the actual clusters
    # Now get meta data about that cluster
    out_d = {}
    if method == "ActPharmaPoint" + " object":
        for kc in kcs:
            out_d[kc.function + "__" + str(kc.pk)] = [x.act_change for x in kc.actpharma_id.all()]
    elif method == "Act3DFrag" + " object":
        for kc in kcs:

src/WebApp/WONKA/templates/WONKA/ShowObs.html
<!DOCTYPE html>
<html lang="en">
  <head>
  {% load staticfiles %}
  <link href="{% static "WONKA/bootstrap.css" %}" media="screen" rel="stylesheet"/>
  <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
  <script src="{% static "WONKA/bootstrap.min.js" %}"></script>
  <script src="{% static "OOMMPPAA/jquery-1.7.min.js" %}"></script>
  <script>
  function isIcmPluginEnabled(){
    var browser = "other";
    var userAgent = navigator.userAgent.toLowerCase();
    
    if(userAgent.indexOf("msie") != -1){
        browser = "msie";
    }
    else
    if (userAgent.indexOf("firefox") != -1) {
        browser = "firefox";
    }
    else
    if (userAgent.indexOf("chrome") != -1) {
        browser = "chrome";
    }
    else
    if (userAgent.indexOf("safari") != -1) {
        browser = "safari";
    }

        if (navigator.plugins && navigator.plugins.length > 0) {
            for (i=0; i < navigator.plugins.length; i++ ) {
                if (navigator.plugins[i].name.toLowerCase().indexOf('molsoft')!= -1){
                    return true;
                }
            }
        return false;
    }
}
		var isplugin = false;
    	$(document).ready(function() {
    	isplugin = isIcmPluginEnabled();
    	if (isplugin==false){
    	document.getElementById("mygetstarted").setAttribute("class","btn btn-lg btn-success disabled");
    	document.getElementById("skiptut").setAttribute("class","btn btn-lg btn-warning disabled");
    	document.getElementById("skiptut2").setAttribute("class","btn btn-lg btn-default dropdown-toggle disabled");
    	document.getElementById("noICMdiv").style.display="";
		};


    	}
    	)
    	
 		  function show_me(my_pk){
		      document.getElementById("ActiveIcmCtl"+my_pk).display="";
			  var ctl =document.getElementById('ActiveIcmCtl'+my_pk);
			  ctl.RunCommands("read binary 'http://163.1.63.28:9010/WONKA/request_observation/?my_pk=my_pk}&me=dl.icb'");
			  ctl.RunCommands("display a_.*li* cpk");
			  ctl.RunCommands("display a_*mol*. wire");
			  ctl.RunCommands("display a_*prot*. xstick");
			  }
			  
			  
function add_comment(){

var my_j = {}
my_j["csrfmiddlewaretoken"] = "{{ csrf_token }}"
my_j["user"] = {{ user.pk }}
my_j["comments"] = document.getElementById('inputComments').value
my_j["observation"] = {{  obs.pk }}
var URL = "{% url 'WONKA:add_comment' %}";
    $.post(URL, my_j, function(response){
        if(response === 'success'){ 
        
        window.location.href = "{% url 'WONKA:ShowObs' obs.pk %}";
        
         }
        else{ alert('Error! :('); }
    });
}



function register(){
  
var my_j = {}
my_j["FirstName"] = document.getElementById('inputFirstName').value
my_j["LastName"] = document.getElementById('inputLastName').value
my_j["EMail"] = document.getElementById('inputEMail').value
my_j["csrfmiddlewaretoken"] = "{{ csrf_token }}"
if(document.getElementById('inputPassword').value==document.getElementById('inputConfPassword').value){

my_j["Password"] = document.getElementById('inputPassword').value
}
else{
alert("Passwords don't match!");
return
}


var URL = "{% url 'WONKA:register_user' %}";
    $.post(URL, my_j, function(response){
alert(response);

 });
  
  }


var OSName="Unknown OS";
if (navigator.appVersion.indexOf("Win")!=-1) OSName="Windows";
if (navigator.appVersion.indexOf("Mac")!=-1) OSName="MacOS";
if (navigator.appVersion.indexOf("X11")!=-1) OSName="UNIX";
if (navigator.appVersion.indexOf("Linux")!=-1) OSName="Linux";

function login(){
  
var my_j = {}
my_j["EMail"] = document.getElementById('inputEMailLOG').value
my_j["csrfmiddlewaretoken"] = "{{ csrf_token }}"
my_j["Password"] = document.getElementById('inputPasswordLOG').value

var URL = "{% url 'WONKA:login_user' %}";
    $.post(URL, my_j, function(response){
alert(response);

 });
  
  }




  </script>
 	<script>

	Module = {
	  memoryInitializerPrefixURL:'{% static "WONKA/lib/" %}',
	  preInit: function() { /*alert('preinit');*/ }
	}
	</script>
	<script src="{% static "WONKA/lib/libicm.js" %}"> </script>
	    
  
  <link rel="stylesheet" href="{% static "WONKA/bootstrap.min.css" %}">
  <link rel="shortcut icon" href="{% static "WONKA/icon.ico" %}" type="image/x-icon">
   <title>WONKA: {{obs.comments}} </title>
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <meta charset="utf-8">
  </head>
  <body> 
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a href="{% url 'WONKA:index'%}" class="navbar-brand">WONKA</a>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="targets">Targets <span class="caret"></span></a>
              <ul class="dropdown-menu" aria-labelledby="themes">
			    {% if targets %}
			      {% for Target in targets %}
			        <li><a tabindex="-1"href="{% url 'WONKA:Summarise' Target.id %}">{{ Target.title }}</a></li>
			      {% endfor %}
			    {% else %}
			    <li><a tabindex="-1" >No targets are available.Make your first?</a></li>
			    {% endif %}
              </ul>
            </li>
            <li>
              <a href="http://www.blopig.com/blog/">Blog</a>
            </li>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="download">Download<span class="caret"></span></a>
                <ul class="dropdown-menu" aria-labelledby="themes">
			       <li><a tabindex="-1"href="https://bitbucket.org/abradley/wonka/wiki/Home">Bitbucket</a></li>
			    </ul>
            </li>
                        <li>
              <a href="{% url 'index' %}">HOME</a>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-left">
            <li><a>{{ target.title }}</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="http://builtwithbootstrap.com/" target="_blank">Built With Bootstrap</a></li>
          </ul>
        </div>
      </div>
    </div>

    <div style="margin-top:50px;"  class="container-fluid">
	      <div class="col-lg-8">
		      <h3>{{obs.author}}:</h3> {{obs.comments}}
		      <div id="ICM-container">
			  <div id="act_div" style="width: 100%; height: 600px; border: 2px solid #ABABAB"></div>
 	   <div style="margin-top:20px;margin-bottom:20px">
          <a class="btn-lg btn-success" href="{% url 'WONKA:Summarise' target.pk %}">BACK TO {{target.title}}</a>
         <a data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Gives ICM a brutal black background" class="btn btn-sm btn-default" onclick="ctl.RunCommands('color background rgb={0,0,0}');">Dark display</a>
          <a data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Gives ICM a shiny white background" class="btn btn-sm btn-default" onclick="ctl.RunCommands('color background rgb={255,255,255}');">White display</a>
          </div>
          </div>
 	  <center>
			  <script>
				//var ctl =document.getElementById('ActiveIcmCtl');
				function onLoadActiveIcm(){
				act = new Module.ActiveIcm("act_div",0,0);
	            //var ctl =document.getElementById('ActiveIcmCtl');
	 			act.OpenProject('{{obs.my_src }}',{})
				 // ctl.RunCommands("read binary '{{obs.my_src }}'");
				  //ctl.RunCommands("display a_*key_water.* xstick  red");
				 // ctl.RunCommands("display a_*key_site.* xstick");
				  //ctl.RunCommands("display a_*key_site.* cpk");
				  //ctl.RunCommands("display a_*RESME*.* xstick");

				  //ctl.RunCommands("display a_*water.* &! a_*key_water.* xstick  blue");
				  //ctl.RunCommands("undisplay a_*water.* cpk");
				  //ctl.RunCommands("display a_url*. xstick");
				  //ctl.RunCommands("undisplay a_url*. cpk");
				  //ctl.RunCommands("display a_*mol*. xstick");
				  //ctl.RunCommands("display a_*prot*. ribbon");
				  
				  //ctl.RunCommands("display Res(Sphere(a_*mol*. a_*prot*. 5.0) & a_*prot*.) xstick");
				  //ctl.RunCommands("display a_*key_*. cpk");
				  //ctl.RunCommands("display a_*ph4. cpk");
				}
				</script>
		  </div>
		 <div style="y-overflow:scroll">

<p></p>

 <div class="col-lg-4" id="disqus_thread"></div>
    <script type="text/javascript">
    // Get the thread ID
    my_url = "http://disqus.com/api/3.0/threads/list.json?api_key={{ public_key }}&forum=wonkadiscuss&thread:ident={{ uniq_id }}"

$.ajax({
  url: my_url,
  beforeSend: function( xhr ) {
    xhr.overrideMimeType( "text/plain; charset=x-user-defined" );
  }
})
  .done(function( data ) {
        var my_j = $.parseJSON(data)
        var my_id = my_j["response"][0]["id"]
        // Now use this to subscrube
        $.ajax({
		  type: "GET",
		  url: "{% url 'WONKA:subscribe_to_disqus' %}",
		  data: {
		    "email": "{{ user.email }}", 
		    "thread": my_id, 
		  },
		  success: function(data){},
		});

});
 
       {% load disqus_tags %}
       {% disqus_sso %}
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = '{{ short_name }}'; // required: replace example with your forum shortname
		var disqus_identifier = "{{ uniq_id }}";

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    
{% if user.is_authenticated %}


{% else %}

	{% endif %}
      </div>
 	  </div>
 	   <center>
      <footer>
        <div class="row">

          <div class="col-lg-12">
            <p>Made by <a href="http://www.dtc.ox.ac.uk/people/11/bradley/">Anthony Bradley</a>. Contact him at <a href="mailto:anthony.bradley@worc.ox.ac.uk">anthony.bradley@worc.ox.ac.uk</a>.</p>
            <p>Code licensed under the <a href="http://www.apache.org/licenses/LICENSE-2.0">Apache License v2.0</a>.</p>
            <p>Based on <a href="http://getbootstrap.com">Bootstrap</a>. Icons from <a href="http://fortawesome.github.io/Font-Awesome/">Font Awesome</a>. Web fonts from <a href="http://www.google.com/webfonts">Google</a>. Favicon by <a href="https://twitter.com/geraldhiller">Gerald Hiller</a>.</p>
          </div>>
        </div>
      </footer>
       </center>
  </body>
 </html>